[package]
name = "olea"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
annotate-snippets = "0.11.4"
anstream = "0.6.18"
chumsky = {version = "1.0.0-alpha.7", features = ["label", "pratt"]}
