[package]
name = "olea"
version = "0.1.0"
edition = "2024"
license = "MIT"
rust-version = "1.85"

[dependencies]
annotate-snippets = "0.11.4"
anstream = "0.6.18"
num = "0.4.3"
num-derive = "0.4.2"
num-traits = "0.2.19"
