file = {decl}

list<item> = {item ","} [item]

decl =
    | "fn" ident "(" list<(ident ty)> ")" ["->" ty] ":" indent {stmt} dedent

stmt =
    | "let" ident [":" ty] "=" expr
    | expr

expr =
    | ident
    | expr "(" list<expr> ")"
    | "(" expr ")"